name = "zxqconsulting-proxy"
main = "proxy-worker.js"
compatibility_date = "2026-06-21"

[[routes]]
pattern = "zxqconsulting.com/*"
zone_name = "zxqconsulting.com"

[[routes]]
pattern = "www.zxqconsulting.com/*"
zone_name = "zxqconsulting.com"
